# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x08metadata\"%\n\x0fMetadataRequest\x12\x12\n\nvideo_code\x18\x01 \x01(\t\"\x81\x01\n\x10MetadataResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x03\x12\x17\n\x0f\x64uration_string\x18\x03 \x01(\t\x12\x11\n\tthumbnail\x18\x04 \x01(\t\x12\x12\n\nview_count\x18\x05 \x01(\x03\x12\x0c\n\x04tags\x18\x06 \x03(\t2W\n\x0fMetadataService\x12\x44\n\x0bGetMetadata\x12\x19.metadata.MetadataRequest\x1a\x1a.metadata.MetadataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METADATAREQUEST']._serialized_start=28
  _globals['_METADATAREQUEST']._serialized_end=65
  _globals['_METADATARESPONSE']._serialized_start=68
  _globals['_METADATARESPONSE']._serialized_end=197
  _globals['_METADATASERVICE']._serialized_start=199
  _globals['_METADATASERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
