---
# Extractor Service Configuration

# Temporary directory for downloaded files
temp_dir: "./tmp"

# Whisper model configuration
whisper_model_size: "tiny" # Options: tiny, base, small, medium, large
whisper_device: "cpu" # Options: cpu, cuda
whisper_compute_type: "int8" # Options: float32, float16, int8

# yt-dlp configuration
ytdlp:
  quiet: true
  no_warnings: true
  ignoreerrors: false
