# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extractor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'extractor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xtractor.proto\x12\textractor\"$\n\x0eYoutubeRequest\x12\x12\n\nyoutube_id\x18\x01 \x01(\t\"\xbd\x01\n\x17YoutubeMetadataResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\nfull_title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x05 \x01(\x05\x12\x17\n\x0f\x64uration_string\x18\x06 \x01(\t\x12\x11\n\tthumbnail\x18\x07 \x01(\t\x12\x0c\n\x04tags\x18\x08 \x03(\t\x12\x12\n\ncategories\x18\t \x03(\t\"=\n\x11TranscriptSegment\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\x12\x0c\n\x04text\x18\x03 \x01(\t\"b\n\x19YoutubeTranscriptResponse\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12.\n\x08segments\x18\x02 \x03(\x0b\x32\x1c.extractor.TranscriptSegment2\xcc\x01\n\x10\x45xtractorService\x12Y\n\x16\x45xtractYoutubeMetadata\x12\x19.extractor.YoutubeRequest\x1a\".extractor.YoutubeMetadataResponse\"\x00\x12]\n\x18\x45xtractYoutubeTranscript\x12\x19.extractor.YoutubeRequest\x1a$.extractor.YoutubeTranscriptResponse\"\x00\x42\x35Z3github.com/dangquyitt/shadowify/proto/gen/extractorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extractor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/dangquyitt/shadowify/proto/gen/extractor'
  _globals['_YOUTUBEREQUEST']._serialized_start=30
  _globals['_YOUTUBEREQUEST']._serialized_end=66
  _globals['_YOUTUBEMETADATARESPONSE']._serialized_start=69
  _globals['_YOUTUBEMETADATARESPONSE']._serialized_end=258
  _globals['_TRANSCRIPTSEGMENT']._serialized_start=260
  _globals['_TRANSCRIPTSEGMENT']._serialized_end=321
  _globals['_YOUTUBETRANSCRIPTRESPONSE']._serialized_start=323
  _globals['_YOUTUBETRANSCRIPTRESPONSE']._serialized_end=421
  _globals['_EXTRACTORSERVICE']._serialized_start=424
  _globals['_EXTRACTORSERVICE']._serialized_end=628
# @@protoc_insertion_point(module_scope)
