services:
  shadowify:
    build:
      context: .
      dockerfile: Dockerfile
    image: dangquyitt/shadowify:latest
    container_name: shadowify
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./configs:/configs
    depends_on:
      - postgres
      - keycloak
    networks:
      - shadowify-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shadowify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shadowify-network

  adminer:
    image: adminer:5
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - adminer-data:/var/lib/adminer
    depends_on:
      - postgres
    networks:
      - shadowify-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: keycloak
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HTTP_PORT=8080
    volumes:
      - ./volumes/keycloak:/opt/keycloak/data/import
    command: "start-dev"
    depends_on:
      - postgres
    networks:
      - shadowify-network

volumes:
  postgres-data:
  adminer-data:

networks:
  shadowify-network:
    driver: bridge
