# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcription.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transcription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\x05proto\")\n\x14GetTranscriptRequest\x12\x11\n\tvideo_url\x18\x01 \x01(\t\"+\n\x15GetTranscriptResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t2b\n\x14TranscriptionService\x12J\n\rGetTranscript\x12\x1b.proto.GetTranscriptRequest\x1a\x1c.proto.GetTranscriptResponseB3Z1github.com/dangquyitt/shadowify/video-service/genb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/dangquyitt/shadowify/video-service/gen'
  _globals['_GETTRANSCRIPTREQUEST']._serialized_start=30
  _globals['_GETTRANSCRIPTREQUEST']._serialized_end=71
  _globals['_GETTRANSCRIPTRESPONSE']._serialized_start=73
  _globals['_GETTRANSCRIPTRESPONSE']._serialized_end=116
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=118
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
