app:
  name: "shadowify"
  version: "1.0.0"
  environment: "prod"
logger:
  level: info
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: shadowify
  sslmode: disable
http:
  port: 8080
youtube:
  apiKey: <your_youtube_api_key>
