# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcriber.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transcriber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transcriber.proto\x12\x0btranscriber\"\'\n\x11TranscribeRequest\x12\x12\n\nvideo_code\x18\x01 \x01(\t\"=\n\x07Segment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x02\"<\n\x12TranscribeResponse\x12&\n\x08segments\x18\x01 \x03(\x0b\x32\x14.transcriber.Segment2c\n\x12TranscriberService\x12M\n\nTranscribe\x12\x1e.transcriber.TranscribeRequest\x1a\x1f.transcriber.TranscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcriber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=34
  _globals['_TRANSCRIBEREQUEST']._serialized_end=73
  _globals['_SEGMENT']._serialized_start=75
  _globals['_SEGMENT']._serialized_end=136
  _globals['_TRANSCRIBERESPONSE']._serialized_start=138
  _globals['_TRANSCRIBERESPONSE']._serialized_end=198
  _globals['_TRANSCRIBERSERVICE']._serialized_start=200
  _globals['_TRANSCRIBERSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
